### ISSUE TITLE
`BuildManager.OnProcessScene` throws a `NullReferenceException` if its `report` argument is `null`

### ISSUE THREAD

**Issue by JesseTG** [sttz/trimmer#14]
According to the docs, [`IProcessSceneWithReport.OnProcessScene`](https://docs.unity3d.com/ScriptReference/Build.IProcessSceneWithReport.html) can have a `null` value for the `report` parameter. The `BuildManager.OnProcessScene` does not handle that case, and so it throws an exception.

**Comment by sttz** [comment]
Fixed by e00e52a.
