### ISSUE TITLE
How to build a single platform on a multi-platform Trimmer profile via command line?

### ISSUE THREAD

**Issue by JesseTG** [sttz/trimmer#3]
Trimmer lets you put multiple platforms in just one build profile.  In the editor, I can build for all platforms in a profile, or for just one at a time.  But what if I want to build for just one platform in a profile from the command line?  How do I do that?

**Comment by sttz** [comment]
The command line build currently builds all platforms in a profile. You'd have to create different build profiles that contain only a single platform.

There's already support for overriding the build path using the «-output» command-line option. The command-line build process could also be changed to respect Unity's existing «-buildTarget» option.

**Comment by JesseTG** [comment]
Ah, okay.  Thank you.  Consider the ability to build just one platform in a multi-platform profile a feature request, then.

**Comment by sttz** [comment]
This has been implemented in version 1.1.0.
